// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginId } from "./PluginId";
import type { SampleType } from "./SampleType";

export type SampleEntry = { isFav: boolean, name: string, } & ({ "source": "native", path: string, } | { "source": "plugin", id: PluginId, url: string, }) & { tags: Array<string>, description: string | null, bpm: number | null, sample_type: SampleType, };
